{% set version = "0.9.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-summarytools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/summarytools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/summarytools/summarytools_{{ version }}.tar.gz
  sha256: 02af1d902bb0f1f9fd83ea743179f920bc952e320b615f824b2b8746a358ec0e

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-base64enc
    - r-checkmate
    - r-dplyr
    - r-htmltools
    - r-lubridate
    - r-magick
    - r-matrixstats
    - r-pander
    - r-pryr
    - r-rapportools
    - r-tibble
    - r-tidyr
  run:
    - r-base
    - r-base64enc
    - r-checkmate
    - r-dplyr
    - r-htmltools
    - r-lubridate
    - r-magick
    - r-matrixstats
    - r-pander
    - r-pryr
    - r-rapportools
    - r-tibble
    - r-tidyr

test:
  commands:
    - $R -e "library('summarytools')"           # [not win]
    - "\"%R%\" -e \"library('summarytools')\""  # [win]

about:
  home: https://github.com/dcomtois/summarytools
  license: GPL-2
  summary: Data frame summaries, cross-tabulations, weight-enabled frequency tables and common descriptive (univariate) statistics in concise tables available in
    a variety of formats (plain ASCII, Markdown and HTML). A good point-of-entry for exploring data, both for experienced and new R users.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: summarytools
# Type: Package
# Title: Tools to Quickly and Neatly Summarize Data
# Version: 0.9.5
# Authors@R: person("Dominic", "Comtois", email = "dominic.comtois@gmail.com", role = c("aut", "cre"))
# Description: Data frame summaries, cross-tabulations, weight-enabled frequency tables and common descriptive (univariate) statistics in concise tables available in a variety of formats (plain ASCII, Markdown and HTML). A good point-of-entry for exploring data, both for experienced and new R users.
# Imports: base64enc, checkmate, dplyr, grDevices, htmltools, lubridate, magick, matrixStats, methods, pander, pryr, rapportools, stats, tcltk, tibble, tidyr, utils
# Suggests: forcats, kableExtra, knitr, magrittr, rmarkdown, rstudioapi
# Depends: R (>= 2.10)
# VignetteBuilder: knitr
# LazyData: true
# License: GPL-2
# URL: https://github.com/dcomtois/summarytools
# BugReports: https://github.com/dcomtois/summarytools/issues
# Encoding: UTF-8
# RoxygenNote: 7.0.2
# NeedsCompilation: no
# Packaged: 2020-02-10 06:57:39 UTC; dominic
# Author: Dominic Comtois [aut, cre]
# Maintainer: Dominic Comtois <dominic.comtois@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-02-10 18:50:03 UTC
