{% set version = '0.9.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-summarytools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/summarytools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/summarytools/summarytools_{{ version }}.tar.gz
  sha256: 7ec7571b496a2054478fd877d64e4f7d1292040eb233b4cb4f0ee76b629c03e1

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcurl
    - r-checkmate
    - r-dplyr
    - r-htmltools
    - r-lubridate
    - r-magick
    - r-matrixstats
    - r-pander
    - r-pryr
    - r-rapportools
    - r-tidyr
  run:
    - r-base
    - r-rcurl
    - r-checkmate
    - r-dplyr
    - r-htmltools
    - r-lubridate
    - r-magick
    - r-matrixstats
    - r-pander
    - r-pryr
    - r-rapportools
    - r-tidyr

test:
  commands:
    - $R -e "library('summarytools')"           # [not win]
    - "\"%R%\" -e \"library('summarytools')\""  # [win]

about:
  home: https://github.com/dcomtois/summarytools
  license: GPL-2
  summary: Data frame summaries, cross-tabulations, weight-enabled frequency tables and common
    univariate statistics in concise tables available in a variety of formats (plain
    ASCII, Markdown and HTML). A good  point-of-entry for exploring data, both for experienced
    and new R users.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: summarytools
# Type: Package
# Title: Tools to Quickly and Neatly Summarize Data
# Version: 0.9.2
# Authors@R: person("Dominic", "Comtois", email = "dominic.comtois@gmail.com",  role = c("aut", "cre"))
# Description: Data frame summaries, cross-tabulations, weight-enabled frequency tables and common univariate statistics in concise tables available in a variety of formats (plain ASCII, Markdown and HTML). A good  point-of-entry for exploring data, both for experienced and new R users.
# Imports: checkmate, dplyr, grDevices, htmltools, lubridate, magick, matrixStats, methods, pander, pryr, rapportools, RCurl, stats, tidyr, utils
# Suggests: rstudioapi, knitr, rmarkdown
# Depends: R (>= 2.10)
# VignetteBuilder: knitr
# LazyData: true
# License: GPL-2
# URL: https://github.com/dcomtois/summarytools
# BugReports: https://github.com/dcomtois/summarytools/issues
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-02-22 00:14:51 UTC; dominic
# Author: Dominic Comtois [aut, cre]
# Maintainer: Dominic Comtois <dominic.comtois@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-02-22 09:10:03 UTC
