travis:
  secure:
    BINSTAR_TOKEN: jgjinJY6x6npkmBtsA9Cat/f8YvL6zaZFJQfqXMwkO7L3hKH5QU4eQSKhaQk+fLWzIuDMs1YOL0kpJrbCAkur5Bf7jodN9smFbLpAAqZVmimxdSDAHiEsLmCqW0A+Rst9vw0Yql1UTzSZFDeuAUGb2/bXtWiFEN2X0PXYGZ5rP88OBYqC3IckzMXYNLDPuhqQBi8FpDl746epTfeLaHLB7difKwyKMfMDng7Da6cy79BZ29MDsPTJ/fUzzVLYKA7UfGL02qF68R6SEFyxBADqrdWUBmQaNDrOyoz3dEDGsyGyPgKf6atuh4HAxR7lOUXnlyIJQsiLa+Y9Fj0RkLEUb6i4aLzyyZlcZjkKMBSwHN7pxSGLUAyK1GzvQMss0pVXYHTmhSZtsDhiIt7NPO7V3truz7cONCNKG3xLXAtcTjsgk5GQT9g4H96YhgOydwu6OAo1hvh3sigHbTYrs1zrSbVlLHLMulql55/J0KXg4Wrjxkib+w+69pabRRBcQxQ8pZQt0qihCfJ/DB5833OwcNDO5ow53ddIue+TED59cLTxnp0BYj6UmicpbTpr1Gc0MNkEdQGWyd5oAqqIAiDXKH2O8jDUsXFqJnfvMm8hNTvsEKiN5ZwDe9VNDQwH0bRD1mRiIjBc7K7W0ep8GnzI3k/EfTjDHEboyXWTqGrIR8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
